Repository xeenoon/DevTools, pull requests merged in 2022-05, with the labels that each got.

#38 Unit tests
  BitCalculator/Extensions.cs
  BitCalculator/Program.cs
  BitCalculator/UnitTest.cs
Labels: bug, enhancement

#40 Fix formatting
  BitCalculator/Program.cs
Labels: enhancement

#46 Logarithims
  BitCalculator/Extensions.cs
  BitCalculator/Help.cs
  BitCalculator/Program.cs
  BitCalculator/UnitTest.cs
Labels: enhancement

#49 Added networking tools
  BitCalculator/ClientNetworking.cs
  BitCalculator/Help.cs
  BitCalculator/Networking.cs
  BitCalculator/Program.cs
  BitCalculator/ServerNetworking.cs
Labels: enhancement

#50 Fix console
  BitCalculator/Extensions.cs
  BitCalculator/Program.cs
Labels: bug

#51 Fix console
  BitCalculator/ClientNetworking.cs
  BitCalculator/Help.cs
  BitCalculator/Program.cs
  BitCalculator/ServerNetworking.cs
Labels: bug, enhancement

#52 Reduced console flicker
  BitCalculator/Program.cs
Labels: bug

#54 Fix console
  BitCalculator/Program.cs
Labels: bug

#59 Error messages
  BitCalculator/Algebra.cs
  BitCalculator/BinaryNumASCI.cs
  BitCalculator/Bitmath.cs
  BitCalculator/CustomConsole.cs
  BitCalculator/Extensions.cs
  BitCalculator/Help.cs
  BitCalculator/Networking.cs
  BitCalculator/Program.cs
  BitCalculator/UnitTest.cs
  BitCalculator/Variables.cs
Labels: bug, documentation, enhancement

#60 Cleaned up code, as specified by Codacy
  BitCalculator/BinaryNumASCI.cs
  BitCalculator/Program.cs
Labels: documentation, enhancement

#66 Fix bitshift
  BitCalculator/Bitmath.cs
  BitCalculator/Program.cs
Labels: bug

#63 Fix console
  BitCalculator/CustomConsole.cs
  BitCalculator/Extensions.cs
  BitCalculator/Help.cs
  BitCalculator/Program.cs
Labels: bug

#72 Pre release bug fixes
  BitCalculator/Bitmath.cs
  BitCalculator/CustomConsole.cs
  BitCalculator/Program.cs
  BitCalculator/UnitTest.cs
Labels: bug
